# Exploring the NBA_API Library

The nba_api is a powerful Python library that provides programmatic access to NBA data sourced directly from NBA.com. Developed and maintained by the community, it allows users to retrieve a wide range of statistics, game logs, player profiles, team data, shot charts, and advanced metrics through a clean and flexible interface. The library is especially popular among data scientists and basketball analysts for building dashboards, conducting performance analysis, and training predictive models.

## Install the library

In [ ]:
!pip install nba_api

Collecting nba_api
  Downloading nba_api-1.10.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from nba_api) (2.0.2)
Requirement already satisfied: pandas>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from nba_api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.11/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1.0->nba_api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1.0->nba_api) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.6.15)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=2.1.0->nba_api) (1.17.0)
Downloading nba_api-1.10.0-py3-none-any.whl (285 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 285.3/285.3 kB 4.2 MB/s eta 0:00:00
Installing collected packages: nba_api
Successfully installed nba_api-1.10.0

In [ ]:
from nba_api.stats.endpoints import leaguedashplayerstats
import pandas as pd

## Player stats

In [ ]:
# Get player stats for the 2024–25 season
stats = leaguedashplayerstats.LeagueDashPlayerStats(season='2024-25')
df = stats.get_data_frames()[0]

# Preview the data
df.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK
0,1630639,A.J. Lawson,A.J.,1610612761,TOR,24.0,26,14,12,0.538,...,383,241,200,327,337,299,375,159,44,364
1,1631260,AJ Green,AJ,1610612749,MIL,25.0,73,44,29,0.603,...,370,99,498,290,214,62,247,281,44,225
2,1642358,AJ Johnson,AJ,1610612764,WAS,20.0,29,8,21,0.276,...,441,312,217,369,347,495,379,281,44,372
3,203932,Aaron Gordon,Aaron,1610612743,DEN,29.0,51,33,18,0.647,...,265,451,301,107,139,41,183,134,44,181
4,1628988,Aaron Holiday,Aaron,1610612745,HOU,28.0,62,39,23,0.629,...,311,224,259,292,292,115,322,281,44,315

## Logs for specific players

In [ ]:
from nba_api.stats.static import players

all_players = players.get_players()

# Search for a player
lebron = [p for p in all_players if p['full_name'] == 'LeBron James'][0]

# LeBron James Player ID
lebron_id = lebron['id']

print(lebron_id)

2544

In [ ]:
from nba_api.stats.endpoints import playergamelog

# Get game logs for the 2024-25 season for Lebron
log = playergamelog.PlayerGameLog(player_id=lebron_id, season='2024-25')
df_log = log.get_data_frames()[0]
df_log[['GAME_DATE', 'PTS', 'REB', 'AST']]

       GAME_DATE  PTS  REB  AST
0   Apr 11, 2025   14    4    8
1   Apr 09, 2025   27    7    3
2   Apr 08, 2025   28    7    3
3   Apr 06, 2025   19    3    7
4   Apr 04, 2025   27    0    8
..           ...  ...  ...  ...
65  Oct 30, 2024   26    6    3
66  Oct 28, 2024   11    5    8
67  Oct 26, 2024   32   14   10
68  Oct 25, 2024   21    4    8
69  Oct 22, 2024   16    5    4

[70 rows x 4 columns]

## Teams

In [ ]:
from nba_api.stats.static import teams

# List all NBA teams
nba_teams = teams.get_teams()
teams_df = pd.DataFrame(nba_teams)
teams_df.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966