# Adult Depression in California

This is a source dataset for a Let's Get Healthy California indicator at "https://letsgethealthy.ca.gov/." This table displays the proportion of adults who were ever told they had a depressive disorder in California. It contains data for California only. The data are from the California Behavioral Risk Factor Surveillance Survey (BRFSS). The California BRFSS is an annual cross-sectional health-related telephone survey that collects data about California residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. The BRFSS is conducted by Public Health Survey Research Program of California State University, Sacramento under contract from CDPH. This indicator is based on the question: "“Has a doctor, nurse or other health professional EVER told you that you have a depressive disorder (including depression, major depression, dysthymia, or minor depression)?” NOTE: Denominator data and weighting was taken from the California Department of Finance, not U.S. Census. Values may therefore differ from what has been published in the national BRFSS data tables by the Centers for Disease Control and Prevention (CDC) or other federal agencies.

## Load the data

In [ ]:
import pandas as pd

In [ ]:
file_path = '' # REPLACE
df = pd.read_csv(file_path)

In [ ]:
df.head()

,Year,Strata,Strata Name,Frequency,Weighted Frequency,Percent,Lower 95% CL,Upper 95% CL
0,2012,Total,Total,1920,NaN,11.74,11.11,12.37
1,2012,Sex,Male,561,1116664.0,8.12,7.32,8.92
2,2012,Sex,Female,1359,2163108.0,15.25,14.30,16.20
3,2012,Race-Ethnicity,White,1314,1806371.0,14.57,13.67,15.46
4,2012,Race-Ethnicity,Black,97,222022.0,13.54,10.44,16.65

## Pivot Tables

In [ ]:
# Pivot Table
pd.pivot_table(data=df[df['Strata'] == 'Race-Ethnicity'], values='Frequency', index='Strata Name', columns='Year')

Year                      2012    2013   2014    2015   2016   2017    2018
Strata Name
Asian/Pacific Islander    61.0    62.0   32.0    58.0   53.0   67.0    73.0
Black                     97.0    93.0   66.0    84.0   91.0   70.0   107.0
Hispanic                 412.0   403.0  299.0   439.0  404.0  394.0   606.0
Other                     36.0    28.0   72.0   106.0   89.0  110.0   118.0
White                   1314.0  1103.0  832.0  1143.0  988.0  903.0  1053.0