# Chemicals in Cosmetics

These data reflect information that has been reported to the California Safe Cosmetics Program (CSCP) in the California Department of Public Health (CDPH). The primary purpose of the CSCP is to collect information on hazardous and potentially hazardous ingredients in cosmetic products sold in California and to make this information available to the public.

For all cosmetic products sold in California, the California Safe Cosmetics Act (“the Act”) requires the manufacturer, packer, and/or distributor named on the product label to provide to the CSCP a list of all cosmetic products that contain any ingredients known or suspected to cause cancer, birth defects, or other developmental or reproductive harm.

To assist companies with reporting, CDPH has compiled a list of reportable ingredients based on lists and reports available from the authoritative scientific bodies cited in the Act to cause cancer or reproductive harm; it is meant to serve as guidance and is not all-inclusive. Companies with reportable ingredients in their products must submit information to the California Safe Cosmetics Program if the company:

Has annual aggregate sales of cosmetic products of one million dollars or more, and
Has sold cosmetic products in California on or after January 1, 2007.
The data table consists of: label names of cosmetic/personal care products, company/manufacturer names, product brand names, product categories, Chemical Abstracts Service registry numbers (CAS#) of the reported chemical ingredients, names of reported chemical ingredients, the number of reported chemicals for each product, and dates of reporting, product discontinuation or reformulation if applicable.

All products containing carcinogens or developmental or reproductive toxicants may not be included due to companies failing to report.

List of reportable ingredients: www.cdph.ca.gov/ReportableIngredientsList

## Load the data

In [ ]:
import pandas as pd
import scipy.stats as sps

In [ ]:
file_path = "" # REPLCACE
df = pd.read_csv(file_path)

In [ ]:
df.head()

,ProductName,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,SubCategory,ChemicalId,ChemicalName,ChemicalCount
0,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",6,Titanium dioxide,1
1,Glover's Medicated Shampoo,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),4,Distillates (coal tar),2
2,Glover's Medicated Shampoo,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),5,Estragole,2
3,PRECISION GLIMMER EYE LINER-ALL SHADES �,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),46,Eyeliner/Eyebrow Pencils,7,Titanium dioxide,1
4,AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),52,Lip Gloss/Shine,8,Titanium dioxide,1

In [ ]:
chem_props = df.groupby('ChemicalName')['ProductName'].nunique().reset_index(name='Count')
chem_props['Proportion'] = chem_props['Count'] / df['ProductName'].nunique()
chem_props.sort_values(by='Proportion', ascending=False)

                                          ChemicalName  Count  Proportion
110                                   Titanium dioxide  29278    0.868371
102  Silica, crystalline (airborne particles of res...   1277    0.037875
40                             Cocamide diethanolamine    791    0.023461
97   Retinol/retinyl esters, when in daily dosages ...    693    0.020554
76                                                Mica    615    0.018241
..                                                 ...    ...         ...
81                             N-Nitrosodiethanolamine      1    0.000030
103                                     Sodium Bromate      1    0.000030
104                                     Spironolactone      1    0.000030
96                                   Retinol palmitate      1    0.000030
116                                      Vinyl acetate      1    0.000030

[123 rows x 3 columns]

## Chi Square Test of Independence

In [ ]:
# Are the chemicals in the cosmetic products independent from the product company?
contingency_tbl = pd.crosstab(df["CompanyName"], df["ChemicalName"])

In [ ]:
# Small p-value indicates we would reject the null (they are not independent)
chi2_stat, p_value, dof, expected = sps.chi2_contingency(contingency_tbl)
p_value

np.float64(0.0)

In [ ]:
contingency_tbl = pd.crosstab(df["CompanyName"], df["ChemicalCount"])

In [ ]:
chi2_stat, p_value, dof, expected = sps.chi2_contingency(contingency_tbl)
p_value

np.float64(0.0)