# Third Grade Math and ELA Scores in Michigan

Third grade English Language Arts (ELA) and Math test results for the 2016-2017 school year by Senate districts for the state of Michigan. Data Driven Detroit obtained these datasets from MI School Data, for the State of the Detroit Child tool in July 2017. Test results were originally obtained on a school level and aggregated to Michigan Senate districts by Data Driven Detroit. Student data was suppressed when less than five students were tested per school. Click here for metadata (descriptions of the fields).

## Load the data

In [ ]:
import pandas as pd

In [ ]:
file_path = "" # REPLACE
df = pd.read_csv(file_path)

In [ ]:
df.head()

,SenateGEOID,ELANumAssessed_Calc,ELATotalMet_Calc,ELATotalNotMet_Calc,MATHNumAssessed_Calc,MATHTotalMet_Calc,MATHTotalNotMet_Calc,ELAPctMet_Calc,MATHPctMet_Calc
0,26001,2769,875,1894,2762,929,1833,0.315999,0.336350
1,26002,3369,825,2544,3413,908,2505,0.244880,0.266042
2,26003,3207,884,2323,3266,1050,2216,0.275647,0.321494
3,26004,2041,503,1538,2041,512,1529,0.246448,0.250857
4,26005,2831,785,2046,2853,804,2049,0.277287,0.281809

## Data Parsing

In [ ]:
# Find the SenateGEOID with the most students passing Math (highest MATHTotalMet_Calc)
df[df['MATHTotalMet_Calc'] == df['MATHTotalMet_Calc'].max()]

,SenateGEOID,ELANumAssessed_Calc,ELATotalMet_Calc,ELATotalNotMet_Calc,MATHNumAssessed_Calc,MATHTotalMet_Calc,MATHTotalNotMet_Calc,ELAPctMet_Calc,MATHPctMet_Calc
29,26030,3151,1968,1183,3160,1989,1171,0.624564,0.62943

In [ ]:
# Find the SenateGEOID with the highest rate of students passing Math (highest MATHPctMet_Calc)
df[df['MATHPctMet_Calc'] == df['MATHPctMet_Calc'].max()]

,SenateGEOID,ELANumAssessed_Calc,ELATotalMet_Calc,ELATotalNotMet_Calc,MATHNumAssessed_Calc,MATHTotalMet_Calc,MATHTotalNotMet_Calc,ELAPctMet_Calc,MATHPctMet_Calc
12,26013,2640,1670,970,2668,1793,875,0.632576,0.672039