# Monthly COVID-19 Hospitalizations

The Coronavirus Disease 2019 (COVID-19) Hospitalization Surveillance Network (COVID-NET) a network that conducts active, population-based surveillance for laboratory-confirmed COVID-19-associated hospitalizations among children and adults. COVID-NET, along with the Respiratory Syncytial Virus Hospitalization Surveillance Network (RSV-NET) and the Influenza Hospitalization Surveillance Network (FluSurv-NET), comprise the Respiratory Virus Hospitalization Surveillance Network (RESP-NET). The RESP-NET platforms have overlapping surveillance areas and use similar methods to collect data. COVID-NET is CDC’s source for important data on rates of hospitalizations associated with COVID-19. Hospitalization rates show how many people in the surveillance area are hospitalized with COVID-19, compared to the total number of people residing in that area.

Data are preliminary and subject to change as more data become available. Data will be updated weekly.

## Load the data

In [ ]:
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
file_path = "" # REPLACE
df = pd.read_csv(file_path)

In [ ]:
df.shape

(41787, 9)

In [ ]:
df.head()

,State,Season,AgeCategory_Legend,Sex_Label,Race_Label,MonthlyRate,Type,Year,Month
0,Utah,2021-22,6mo-<12 months,All,All,39.7,Crude Rate,2021,11
1,Utah,2021-22,6mo-<12 months,All,All,0.0,Crude Rate,2021,10
2,Utah,2021-22,6mo-<12 months,All,All,53.0,Crude Rate,2022,2
3,Utah,2021-22,6mo-<12 months,All,All,74.0,Crude Rate,2022,6
4,Utah,2021-22,6mo-<12 months,All,All,29.6,Crude Rate,2022,8

In [ ]:
df['AgeCategory_Legend'].value_counts()

AgeCategory_Legend
0-17 years (Children)    8095
All                      7736
≥18 years (Adults)       7416
5-11 years                927
≥65 years                 927
6mo-<12 months            927
12-17 years               927
≥75 years                 927
1-4 years                 927
18-29 years               927
1-<2 years                927
40-49 years               927
18-49 years               927
75-84 years               927
5-17 years                927
2-4 years                 927
65-74 years               927
0-<1 year                 927
0-<6 months               927
≥85 years                 927
50-64 years               927
0-4 years                 927
30-39 years               927
Name: count, dtype: int64

## Groupby Method

In [ ]:
df.groupby('State')['MonthlyRate'].mean().sort_values(ascending=False)

In [ ]:
plt.figure(figsize=(20, 6))
sb.boxplot(x=df['State'], y=df['MonthlyRate'], showfliers=False)

In [ ]:
df.groupby('AgeCategory_Legend')['MonthlyRate'].mean().sort_values(ascending=False)

In [ ]:
df.groupby('Sex_Label')['MonthlyRate'].mean().sort_values(ascending=False)

In [ ]:
df.groupby('Race_Label')['MonthlyRate'].mean().sort_values(ascending=False)

## Two Sample t-test

In [ ]:
# Difference of means Hypothesis Test for if men were hospitalized more frequently on average for COVID than women
male = df[df['Sex_Label'] == 'Male']['MonthlyRate'].dropna()
female = df[df['Sex_Label'] == 'Female']['MonthlyRate'].dropna()
sem = np.sqrt(male.var()/len(male) + female.var()/len(female))
z = (male.mean() - female.mean()) / sem
z

In [ ]:
# Difference of means Hypothesis Test for if people ≥85 years were hospitalized more frequently on average for COVID
older = df[df['AgeCategory_Legend'] == '≥85 years']['MonthlyRate'].dropna()
all = df[df['AgeCategory_Legend'] == 'All']['MonthlyRate'].dropna()
sem = np.sqrt(older.var()/len(older) + all.var()/len(all))
z = (older.mean() - all.mean()) / sem
z